### ISSUE TITLE
auto dump-autoload 

### ISSUE THREAD

**Issue by devmsh** [cleaniquecoders/packager#1]
what about auto run 
```
composer dump-autoload
```

after a successful hook? so the project can directly use the package without manually run the command?

**Comment by nasrulhazim** [comment]
I have updates on this package on my local, including the documentation. Will push the commits soon.  :)

**Comment by devmsh** [comment]
Thanks, please close the issue once you push the commits ;)

**Comment by nasrulhazim** [comment]
Hi @devmsh ,

You may update your package - I've made a little upgrade with stubs and I have included Orchestra/Testbench. So you don't need actually to hook with a Laravel application to test your package. 

Closing this issue.
